version: '3.8'

name: case_study_inventory
services:
  #CONTAINER SHOULD BE CREATED FIRST
  db:
    container_name: SQL-Server
    restart: always
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=qwertyu1*
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "bash", "-c", "(/opt/mssql-tools/bin/sqlcmd -U sa -P qwertyu1* -Q 'SELECT 1') || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  assetapi:
    container_name: Asset-API
    image: ${DOCKER_REGISTRY-}assetapi
    ports:
        - "55008:443"
    build:
      context: .
      dockerfile: AssetAPI/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  invoicegeneratorapi:
    container_name: Invoice-Generator-API
    image: ${DOCKER_REGISTRY-}invoicegeneratorapi
    ports:
        - "55010:443"
    build:
      context: .
      dockerfile: InvoiceGeneratorAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  invoiceapi:
    container_name: Invoice-API
    image: ${DOCKER_REGISTRY-}invoiceapi
    ports: 
        - "55006:443"
    build:
      context: .
      dockerfile: InvoiceAPI/Dockerfile
      args:
        - USERPROFILE=usermaltem
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development